# Generated by Django 5.2.7 on 2025-11-12 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_user_user_type_feepayment_classfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Mobile Money')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='processed_by',
            field=models.ForeignKey(limit_choices_to=models.Q(('user_type__in', ['bursar', 'admin'])), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
