# Generated by Django 5.2.7 on 2025-11-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_feepayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Mobile Money'), ('momo_pay', 'MoMo Pay')], max_length=20),
        ),
    ]
