# Generated by Django 5.2.7 on 2025-11-12 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_student_photo_teacher_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'academic_years',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='promotion_rank',
            field=models.IntegerField(default=0, help_text='Order used for automatic promotion across years'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_graduated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('promoted', 'Promoted'), ('repeating', 'Repeating'), ('graduated', 'Graduated')], default='enrolled', max_length=10)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('override_status', models.CharField(blank=True, choices=[('enrolled', 'Enrolled'), ('promoted', 'Promoted'), ('repeating', 'Repeating'), ('graduated', 'Graduated')], max_length=10, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                ('class_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
            options={
                'db_table': 'enrollments',
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
